[workspace]
members = ["simple-server-analytics", "simple-server-analytics-db"]
resolver = "2"

[workspace.dependencies]
salvo = { git = "https://github.com/SpaceEraser/salvo.git" }
simple-id = { git = "https://github.com/SpaceEraser/simple-id" }
